ktor:
    deployment:
        port: ${PORT:8080}   # Render asigna el puerto en la variable de entorno
        watch:
            - classes
            - resources
    application:
        modules:
            - com.adamar.ktor.ApplicationKt.module

logging:
    level: INFO



